name: Generate manifests

# ① 퍼미션 선언
permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'
      - 'Icon/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ② checkout 시 토큰 전달
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Generate images.json and icons.json
        run: |
          ls images/*.{jpg,jpeg,png} 2>/dev/null \
            | xargs -n1 basename \
            | jq -R -s -c 'split("\n")[:-1]' > images/images.json
          ls Icon/*.{svg,png,jpg} 2>/dev/null \
            | xargs -n1 basename \
            | jq -R -s -c 'split("\n")[:-1]' > Icon/icons.json

      - name: Commit manifests
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add images/images.json Icon/icons.json
          git commit -m "chore: update image/icon manifests" || echo "no changes"
          git push
