name: Generate manifests

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'
      - 'Icon/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Generate JSON Manifests without jq
        run: |
          #— images/images.json 생성
          echo -n '[' > images/images.json
          first=true
          for f in images/*.{jpg,jpeg,png}; do
            [ -e "$f" ] || continue
            name="${f##*/}"
            if [ "$first" = true ]; then
              first=false
            else
              echo -n ',' >> images/images.json
            fi
            printf '%s' "\"$name\"" >> images/images.json
          done
          echo ']' >> images/images.json

          #— Icon/icons.json 생성
          echo -n '[' > Icon/icons.json
          first=true
          for f in Icon/*.{svg,png,jpg}; do
            [ -e "$f" ] || continue
            name="${f##*/}"
            if [ "$first" = true ]; then
              first=false
            else
              echo -n ',' >> Icon/icons.json
            fi
            printf '%s' "\"$name\"" >> Icon/icons.json
          done
          echo ']' >> Icon/icons.json

      - name: Commit Manifests
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add images/images.json Icon/icons.json
          git commit -m "chore: update manifests" || echo "No changes to commit"
          git push
